### ISSUE TITLE
Responding to Media Queries on window resize in React Native Web

### ISSUE THREAD

**Issue by haveamission** [vitalets/react-native-extended-stylesheet#152]
Is there a way to respond to window resize events and automatically re-calculate all of the Media Queries for the new window size?

**Comment by vitalets** [comment]
@haveamission This is related to dynamic theme change, see [#caveats](https://github.com/vitalets/react-native-extended-stylesheet#caveats). You can manually subscribe to `resize` event and rebuild styles. The problem is how to re-render all components of the app. Please see https://github.com/vitalets/react-native-extended-stylesheet/issues/47#issuecomment-314760557 for details.
