### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by jsartisan** [vitalets/react-native-extended-stylesheet#154]
Hi there, great work with this repo.

I recently created a UI library and want to include support for media queries too in it and I was thinking to use your library for it - https://magnus-ui.com/
Before I do that, I wanted to know are you doing active development on this library?

**Comment by juriuschakow** [comment]
lol i just came here to ask the same question 😂😂
but i've got one more question:
is this library actually also minding the dp problem scale factor problem? explained here https://medium.com/react-native-training/build-responsive-react-native-views-for-any-device-and-support-orientation-change-1c8beba5bc23
if this library is also minding this problem then this library is the hottest underrated library because it's so awesome

i hope too that it is still maintained. i wanted to use it now too for my app

**Comment by jsartisan** [comment]
@vitalets any update? I really want to use this library and build an ecosystem with this.

**Comment by vitalets** [comment]
Hey @jsartisan!

Currently I would say that is't not active, unfortunately(
I'd suggest to check [alternatives](https://github.com/jondot/awesome-react-native#styling) for your UI library or maybe use plain StyleSheet objects.

**Comment by ni3ra5** [comment]
This looked really cool.
Will this ever get active again or does it have any equivalent alternatives ?

**Comment by reichhartd** [comment]
For those encountering issues due to the original library's lack of recent updates, our fork of `react-native-extended-stylesheet` might offer some solutions. While it is not actively maintained, it includes several enhancements such as IntelliSense IDE integration, updated dependencies, TypeScript support, and compatibility with both CommonJS and ESmodules.

If you're interested in utilizing these improvements or using the fork as a reference for further development, you can find it here: [tokenstreet/react-native-extended-stylesheet](https://github.com/tokenstreet-tech/react-native-extended-stylesheet)

Please note that while the fork isn’t being actively developed, it remains available for inspiration or as a base for your own enhancements.
